name: Build and Publish

on:
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**'
    tags:
      - '*'
  workflow_dispatch:

defaults:
  run:
    working-directory: backend/

jobs:
  run:
    uses: ticketsbot-cloud/template/.github/workflows/template.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      package_name: api
      sha: ${{ github.sha }}
    secrets: inherit
